name: theme_extensions_generator
description: Code generation for theme extensions
version: 2.0.0
repository: https://github.com/MiiMan/theme_extensions_generator

environment:
  sdk: '>=3.4.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  build: any
  analyzer: ^7.0.0
  source_gen: ^3.0.0
  theme_extensions_annotation: ^1.1.1

dev_dependencies:
  build_test: any
  build_runner: any
  lints: ^2.0.0
  test: ^1.21.0
